### ISSUE TITLE
index outside the array

### ISSUE THREAD

**Issue by defector1234** [cap9/EEPhysics#12]
An unhandled exception of type 'System.IndexOutOfRangeException' occurred in EEPhysics.dll

Additional information: Index was outside the bounds of the array.

Every time i try to connect to ee, it goes into break mode and throws this exception.

**Comment by defector1234** [comment]
found the source

The first comment i used a dll.

On physics world.cs this is giving the exception. 
   int rot = blockData[x][y] == null ? 1 : blockData[x][y][0];

**Comment by EEJesse** [comment]
Fixed within the latest update. [1.4.2](https://github.com/cap9/EEPhysics/commit/94330e2f7051393c8c66ab4461cd35c705b4b12c)

Sorry for the late reply.
