### ISSUE TITLE
EE Physics System Failure

### ISSUE THREAD

**Issue by SirJosh3917** [cap9/EEPhysics#14]
It says a cast is invalid or something (so i think something like '''(int)"bad cast"'''' ) and I cant recompile this since it's using freaking c# 6.0 lambda expressions!!!!!!!!!!

**Comment by EEJesse** [comment]
I can't seem to replicate this error. Can you tell me where this error occurs?

**Comment by atillabyte** [comment]
This isn't really an issue.
If you wish to target a lower .NET framework, feel free to contribute to the project.

**Comment by SirJosh3917** [comment]
I'd love to help you guys replicate the error, but it just seems to appear "randomly" for no proper reason at all, although I know for sure that it doesn't just happen randomly. I'll attempt to give you details in a while
