### ISSUE TITLE
Can't find EEPhysics.pdb

### ISSUE THREAD

**Issue by den3107** [cap9/EEPhysics#9]
I have installed this library through NuGet with Visual Studio Express 2013.
Visual studio gives the following symbol error:
EEPhysics.pdb contains the debug information required to find the source for the module EEPhysics.dll.

It tries to find EEPhysics.pdb in the folder
`C:\Users\Public\Documents\EEPhysics\EEPhysics\obj\Release\EEPhysics.pdb`
Though I don't even have the folder
`C:\Users\Public\Documents\EEPhysics\`

Searching though my laptop I can't find any file added named EEPhysics.pdb.

Addition:
It goes wrong once I add
`physicsWorld.HandleMessage(m);`
to onMessage.

**Comment by den3107** [comment]
After compiling the file manually I managed to get the .pdb, though now when I use the .cs files from the download, there comes an error at PhysicsPlayer.cs line 1000
int _loc3_ = HostWorld.GetBlockData(x, y)[0];
Message:
Object reference not set to an instance of an object.

I have yet made no actions with EEPhysics, just added it to the onMessage function.

**Comment by cap9** [comment]
The bug should now be fixed. (sorry for being slow) The nuget package didn't have .pdb file because it's only for debugging, but now it's uploaded with SymbolSource.
